services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MARIADB_DATABASE=dcu
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
    ports:
      - '3306:3306'
