# Application name
spring.application.name=docker-container-updater

# Dotenv
spring.config.import=optional:file:.env[.properties]

# Server Settings
server.port=8080

# Frontend
spring.web.resources.static-locations=file:./frontend/dist/
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.profiles.active=dev

spring.devtools.restart.enabled=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true